/*
 * Copyright (c)
 * @website: http://arresto.in/
 * @author: Arresto Solutions Pvt. Ltd.
 * @license: http://arresto.in/
 *
 * The below module/code/specifications belong to Arresto Solutions Pvt. Ltd. solely.
 */

package app.com.arresto.Flavor_Id;

public interface FlavourInfo {
    String Fl_CLIENT_ID = "947";
    String PACKAGE_NAME = "app.com.dewalt";
    String APP_ID = "app.com.dewalt";
    double distance_unit = 1.0;
    String unit_name = "km";
    String date_format = "dd-MM-yyyy hh:mm: a";
    String Base = "https://arresto.in";
    String HOST = Base + "/connect/";
    String webData = "<html>" +
            "<p><strong>DFP Safety Vault Terms of Use</strong></p>" +
            "<p>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THE DFP SAFETY VAULT MOBILE APPLICATION (THE \"<u>APPLICATION \"</u>). YOUR ACCEPTANCE OF AND AGREEMENT TO ABIDE BY ALL OF THE TERMS OF USE GOVERNING YOUR USE OF THE APPLICATION AND ANY MATERIALS CONTAINED THEREIN IS A CONDITION OF YOUR RIGHTS TO FURTHER ACCESS ANY AND ALL MATERIALS CONTAINED IN OR ACCESSED THROUGH THE APPLICATION. IF YOU DO NOT AGREE WITH THESE TERMS OF USE, PLEASE DO NOT USE THE APPLICATION.</p>" +
            "<p>It is recommended that you keep a copy of these Terms of Use and any licenses posted within or through the Application for your records, as they may change from time-to-time as added functions and services are incorporated into the Application. Your rights to use this Application and any Software, Data, or Documentation are restricted rights that are governed by the End User License Agreement contained herein and include restrictions on use and transfer.</p>" +
            "<ol>" +
            "<li><strong><u>General</u></strong>. The Application is owned and operated by or on behalf of DFP Safety Corporation, a Delaware corporation (\"\"<u>DFP Safety</u>\"\"). By accessing, receiving, downloading, syncing, using, or possessing or continuing to access, receive, download, sync, use, or possess software, user interfaces, applications, and associated media (<u>Software</u>) for use via the Internet, or via wireless or other handheld or mobile devices (<u>Hardware</u>), printed, online, and electronic materials associated therewith (<u>Documentation</u>) and data, materials, and content (<u>Data</u>) (collectively Software, Data, and Documentation to be known as <u>Services</u> herein) submitting a registration form, or clicking the \"I Agree\" or \"Continue\" buttons when prompted and completing the registration form, you are entering into these Terms of Use with DFP Safety, and you hereby acknowledge and agree to the validity and applicability of the Terms of Use governing this Application, the Privacy Policy, any applicable Provider Terms, and agree to be bound hereto. You further agree to conduct transactions with DFP Safety by electronic means and that your electronic signature is the legally binding equivalent to your handwritten signature and that you will not, at any time in the future, repudiate the meaning or effectiveness of your electronic signature or claim that your electronic signature is not legally binding.</li></br>" +
            "<li><strong><u>Fees</u></strong>. Please be advised that the Application is not a fee-based service.</li></br>" +
            "<li><strong><u>Use of Service</u></strong>. You agree that the Application and its services are furnished and shall be used solely for your personal, business, or institutional use, and are subject to these Terms of Use. Such permitted uses do not include the right to directly or indirectly transmit, broadcast, redistribute, forward, or deliver the Services or any part of the data, information, images or other products which constitute the Application, or Services to any other person or entity, in any format (including, but not limited to, framing, deep liking, or embedding), or by any means (<u>Commercial Use</u>), absent a supplemental agreement in writing with DFP Safety. The Application and its Services may be used for lawful purposes only and may not be used in a manner that violates or infringes DFP Safety&rsquo;s expressly reserved rights, the rights of DFP Safety's Providers, as defined below, the rights of any third parties, or applicable law. You agree to use the Application consistent with these Terms of Use and shall not disclose your password to any unauthorized person. You shall be fully responsible for maintaining confidentiality of account access information and for all charges made to your account.</li></br>" +
            "<li><strong><u>Access</u></strong>. Access to the Application is contingent upon you providing all equipment necessary to access the Internet, Services, or services offered by DFP Safety. Access to the Application requires the use of a mobile device meeting the minimum specifications of DFP Safety. The Application and use of the DFP Safety Services and services through the Application is usually available 24 hours a day, 7 days a week; however, DFP Safety reserves the right to make the Application unavailable from time-to-time for any reason and at any time without prior notice. You agree that DFP Safety shall not be liable for any damages arising from any interruption, suspension, or termination of the Application. If applicable, the Services supplied by DFP Safety may be made available on any Application or Applications DFP Safety shall designate (<u>Designated Application</u>). Your options as to which Services are available, and how to move Services from the Designated Application to your location or Hardware, or to issue appropriate electronic commands to accept the Services at the Designated Application and move such items to an authorized location or to pass on authorized users to the Designated Application are limited by the type or format of the Services or services selected by you and your Hardware then in use. DFP Safety makes no guarantees that the Services or services selected by you will be operational with your Hardware.</li></br>" +
            "<li><strong><u>Permitted Uses</u>.</strong> If applicable, you may download, view, and copy Data incorporated in or accessed through this Application subject to the following: (1) the Data may be used solely for personal, informational, or internal purposes and may not be re-distributed without the express written permission of DFP Safety; (2) the Data may not be modified or altered in any way; (3) any copyright or other proprietary notices must appear on all copied Data; and (4)&nbsp;certain Data on this Application may be subject to further use, modification, copying, or dissemination restrictions that shall override this general grant to use the Services (please see the Notice Specific to Services Available on this Application section herein). Access to and copying/distribution of original user content (i.e. such as from chat rooms, message/bulletin boards, photo gallery, feedback forums, etc.) shall be controlled by restrictions imposed by the originator of the content or by the Acceptable Use Policy. Except as expressly provided herein, you may not use, download, upload, copy, print, display, perform, reproduce, publish, license, post, transmit, distribute, or redistribute any information or Services from the Application in whole or in part without the prior written permission of DFP Safety or its Providers, which DFP Safety reserves the right to grant or deny as it sees fit in its sole discretion. Requests to reprint or redistribute Services and other materials accessed from the Application should be directed to the originator of the Services or materials.</li></br>" +
            "<li><strong><u>Intellectual Property</u></strong>.Information furnished by DFP Safety to you is intended for your sole and exclusive use and shall be considered proprietary information, the ownership of which shall remain with DFP Safety or its Providers. All Services, information, Data, images, and other things comprising the services are to be considered copyrighted by DFP Safety, its Providers, or the content originator, as the case may be, and they remain the sole and exclusive property of such persons. You are authorized to use such for the purposes stated herein and to store such information during the term hereof. You may not store for future use such information beyond that period, nor develop a library of such information. You agree not to copy Data on the Application, except as permitted under these Terms of Use, not to reverse engineer or break into the Application, and not to use the Application materials, Services, or services to violate law, the Notice Specific to Services Available on this Application, DFP Safety&rsquo;s Privacy Policy, or these Terms of Use. REGARDLESS OF ANY OTHER PROVISION HEREIN, THE TRADEMARK OF DFP SAFETY SHALL NOT BE USED BY YOU IN ANY WAY, ESPECIALLY NOT AS A MEANS OF IDENTIFYING THE SOURCE OF THE SERVICE TO PUBLIC AUDIENCES OR CLIENTELE WITHOUT A SPECIFIC LICENSE TO DO SO FROM DFP SAFETY.</li></br>" +
            "<li><strong><u>Trademark Information</u></strong>.DFP SAFETY, DFP Safety Vault and all other DFP Safety Product names, service names, slogans, or logos referenced in this Application are trademarks or registered trademarks of DFP Safety Corporation, a Delaware corporation. All other company, product, or service names referenced in this Application are used for identification purposes only and may be trademarks of their respective owners.</li>" +
            "<br>" +
            "<li><strong> <u>Copyright Information</u>. Copyright &copy; 2022, </strong>DFP Safety. All rights reserved. Original user content submitted by users or Providers to the Application or where expressly provided otherwise by DFP Safety is proprietary to the submitting users or Providers, is protected by copyright law, and is subject to the usage restrictions separately set forth in the Notice Specific to Services Available on this Application.</li>" +
            "<p>Notification of Copyright Infringement:</p>" +
            "<p>DFP Safety will, in appropriate circumstances, remove or disable access to related content or terminate the accounts of persons or entities involved in disputes regarding intellectual property rights. If you believe that this Application contains infringing or disputed intellectual property, or that work has been used or copied in a way that constitutes copyright infringement and such infringement is occurring on this Application or on Applications linked to from this Application, please provide DFP Safety&rsquo; Copyright Agent a Notice of Infringing Material(s) (<u>Notice</u>) containing the following elements:</p>" +
            "<ol>" +
            "<li>A physical or electronic signature of the owner (or an authorized agent) of the copyright material(s) alleged to have been infringed.</li>" +
            "<li>A description of the copyrighted work or works that the copyright owner or agent claims have been infringed and a reasonable identification of the material(s) the copyright owner claims is infringing the copyrighted work(s) and is requesting to be removed or access be disabled.</li>" +
            "<li>A description of where the alleged infringing material(s) is located on the Application (include a URL, if possible).</li>" +
            "<li>Sufficient contact information regarding the copyright owner or agent, such as physical address, e-mail address, website, telephone number, and fax number.</li>" +
            "<li>A statement by the copyright owner or agent that he/she has a good faith belief that the use of the material(s) identified in the Notice is not authorized by the copyright owner, its agent, or the law.</li>" +
            "<li>A statement by the copyright owner or agent that the information in the Notice is accurate and, under penalty of perjury, that the complainant is the copyright owner or an authorized agent to act on behalf of the copyright owner.</li>" +
            "</ol>" +
            "<p>DFP Safety&rsquo;s Copfor Notices of Infringing Materials can be reached as follyright Agent ows:</p>" +
            "<p>By Mail:support@dfpsafetyvault.com</p>" +
            "<p>Attn: Copyright Agent</p>" +
            "<p>DFP Safety Corporation</p>" +
           
            "<li><strong><u>Acceptable Use Policy</u></strong><strong>.</strong> You agree not to use the Application, Services, or services to:</li>" +
            "<ul>" +
            "<li>upload, post, or otherwise transmit any data or content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy or without another's permission, hateful, or racially, ethnically, or otherwise objectionable to any person for any reason, natural, or corporate;</li>" +
            "<li>harm minors in any way; impersonate any person or entity, including, but not limited to, an DFP Safety representative, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>" +
            "<li>upload, post, or otherwise transmit any falsified, composite, or otherwise non-authentic depictions of events, entities, or persons (spoofs);</li>" +
            "<li>upload, post or otherwise transmit any content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary, and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>" +
            "<li>upload, post, or otherwise transmit any content that infringes any patent, trademark, trade secret, copyright, or other proprietary or intellectual property rights of any party;</li>" +
            "<li>upload, post, or otherwise transmit any content that promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age;</li>" +
            "<li>upload, post, or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, \"junk mail,\" \"spam,\" \"chain letters,\" \"pyramid schemes,\" \"phishing,\" or any other form of solicitation, including, without limitation, the solicitation of users to become users of other online information services competitive with DFP Safety;</li>" +
            "<li>upload, post, or otherwise transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</li>" +
            "<li>interfere with or disrupt DFP Safety or servers or networks connected to DFP Safety, or disobey any requirements, procedures, policies, or regulations of networks connected to DFP Safety;</li>" +
            "<li>\"stalk\" or otherwise harass another; collect or store Personally Identifiable Information about other users;</li>" +
            "<li>promote or provide instructional information about illegal activities, promote physical harm or injury against any group or individual, or promote any act of cruelty to animals, including, but not limited to, providing instructions on how to assemble bombs, grenades, and other weapons;</li>" +
            "<li>use your access or DFP Safety-hosted Application as storage for remote loading or as a door or signpost to another home page, whether inside or beyond the Application, without express written permission from DFP Safety;</li>" +
            "<li>use the Application to engage in commercial activities without enrolling in DFP Safety-approved programs, including but not limited to, offering for sale any products or services, soliciting for advertisers or sponsors, conducting raffles or contests that require any type of entry fee, displaying a sponsorship banner of any kind, displaying banners for services that provide cash or cash-equivalent prizes to users in exchange for hyperlinks to their website, use the Application to provide access to the Application for other persons through use of your User Name and Password; or</li>" +
            "<li>tamper in any way with the Services or functionality of the Application, such as placing on the Application material that contains any viruses, time bombs, trojan horses, worms, Easter eggs, cancelbots, or other computer programming routines that may damage, interfere with, intercept or expropriate any system, data or information, or utilize bots, agents, auction crawlers, and other computer-based crawling programs on the Application.</li>" +
            "</ul>" +
            "<p>DFP SAFETY EXPRESSLY DISCLAIMS ANY AND ALL LIABILITY FOR ANY MATERIALS UPLOADED OR PLACED ON THE APPLICATION BY YOU OR OTHER USERS OF THE APPLICATION.</p>" +
            "<li><strong> <u>Notice Specific to Services Available on this Application</u>.</strong> Permission to use Data from this Application is granted, provided that: (1) appropriate copyright notices appear in all copies; (2) use of such Data from this Application is for your use only and will not be copied or posted on any network computer or broadcast in any media absent an express written agreement with DFP Safety; (3) the Data shall not be used outside of this Application absent an express written agreement with DFP Safety and shall be in compliance with these Terms of Use; (4) no unauthorized modifications of any Services are made; (5) to the extent modifications are made, a notice of modification including the subject matter of modification appear with the modified Services; and (6) any use of Provider Services is consistent with any applicable Provider Terms. Use for any other purpose is expressly prohibited by law and may result in civil and criminal penalties. Subject to DFP Safety&rsquo;s Privacy Policy, or where expressly provided otherwise by DFP Safety, all comments, feedback, photographs, videos, information, or materials submitted to DFP Safety through or in association with this Application shall be considered non-confidential and property of DFP Safety. By submitting such comments, feedback, PHOTOGRAPHS, VIDEOS, information, or materials to DFP SAFETY, you AUTOMATICALLY GRANT DFP SAFETY a royalty-free, unlimited, irrevocable LICENSE to all worldwide rights, title, and interest in any copyrights or other intellectual property rights to the comments, feedback, PHOTOGRAPHS, VIDEOS, information, or materials. DFP SAFETY shall be free to use such comments, feedback, PHOTOGRAPHS, VIDEOS, information, or materials on an unrestricted basis. FOR YOUR CONVENIENCE, DFP SAFETY MAY MAKE AVAILABLE ON THIS APPLICATION OR IN ITS SERVICES, TOOLS, AND UTILITIES FOR USE OR DOWNLOAD. DFP SAFETY DOES NOT MAKE ANY ASSURANCES WITH REGARD TO THE ACCURACY OF THE RESULTS OR OUTPUT THAT DERIVES FROM SUCH USE OF ANY SUCH TOOLS AND UTILITIES. PLEASE RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS WHEN USING THE TOOLS AND UTILITIES MADE AVAILABLE ON THIS APPLICATION OR IN DFP SAFETY SERVICES. Services, as specified above, do not include original user content hosted on this Application, the design or layout of the Application, or any other DFP Safety owned, operated, licensed, or controlled Application. Elements of the Application are protected by copyright, patent, trade dress, trademark, unfair competition, and other laws and may not be copied or imitated in whole or in part. No logo, graphic, sound, or image from any Application may be copied or retransmitted unless expressly permitted by DFP Safety, its Providers, or the originating user associated with original user content displayed on this Application.</li></br>" +
            "<li><strong><u>Additional Services</u></strong><strong>.</strong> Certain services, in addition to those described in these Terms of Use, or as offered by DFP Safety through other product licenses or service agreements and others as may be made available as a part thereof, or through this Application, by Providers, or by DFP Safety, and may be subject to terms and conditions in addition to those in these Terms of Use, which terms and conditions are available upon registering for or subscribing to the products or service(s) (<u>Provider Terms</u>). Any Provider Terms are in addition to these Terms of Use and apply only to that Provider's service or content unless explicitly stated otherwise. Should an additional service be made available on this Application or from DFP Safety without additional Provider Terms, these Terms of Use shall apply. TO THE EXTENT THAT DFP SAFETY SERVICES ARE BEING MADE AVAILABLE THROUGH THIS APPLICATION, THE PROVISIONS IN THESE TERMS OF USE SHALL MODIFY OR AMEND ANY CONFLICTING TERMS IN OTHER DFP SAFETY AGREEMENTS. Additional Provider Terms for any products or services provided with DFP Safety registration may be made available through the Application via hyperlinks and are applicable should you choose to use their products or services.</li></br>" +
            "<li><strong> </strong><strong><u>Safety</u></strong>. You will not access or use the Application while operating a motor vehicle in a manner that violates any traffic law, rule, or regulation. Even if access or uses of the Application while operating a motor vehicle is permitted by applicable law, DFP Safety does not recommend accessing or using the Application while driving without a hands-free technology; provided, however such technology is not a substitute for attentive driving nor guaranty of safety. It is your sole responsibility to exercise discretion and observe all safety measures required by law, traffic rules, and traffic regulations.</li></br>" +
            "<li><strong> <u>Disclaimer</u>.</strong> DFP Safety shall have no responsibility or liability whatsoever to you or any other person or entity, parties, and nonparties alike, related to the Application or any Services or services. DFP Safety shall have no responsibility or liability whatsoever when data or services from third parties that DFP Safety uses for its Application or any Services or services are unavailable or disregarded. Web-based and mobile/wireless services are dependent upon open communications networks provided by third parties and DFP Safety is not responsible for lack of services due to communications network outages. DFP Safety makes no warranty or representation with respect to any Provider products or materials.</li></br>" +
            "<li><strong><u>NO WARRANTIES; LIMIT OF LIABILITY</u></strong>. YOU ASSUME ALL RESPONSIBILITY AND RISK FOR THE USE OF THIS APPLICATION, ERRORS IN THE APPLICATION, AND THE INTERNET GENERALLY. THIS APPLICATION AND THE SERVICES ARE PROVIDED BY DFP SAFETY ON AN \"AS IS\" BASIS. DFP SAFETY AND ITS PROVIDERS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE APPLICATION OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS APPLICATION. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, DFP SAFETY AND ITS PROVIDERS DISCLAIM ALL WARRANTIES, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE AND FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OR OTHER PROPRIETARY RIGHTS, AND FREEDOM FROM ERRORS, VIRUSES, BUGS, OR OTHER HARMFUL COMPONENTS. YOU UNDERSTAND AND AGREE THAT YOU DOWNLOAD, INSTALL, OR USE ANY PRODUCTS MADE AVAILABLE ON THE APPLICATION AT YOUR OWN DISCRETION AND RISK AND THAT DFP SAFETY WILL HAVE NO LIABILITY TO YOU OR ANY OTHER PERSON FOR ANY DAMAGES OR DISRUPTION TO YOUR COMPUTER OR SYSTEM OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOADS. DFP SAFETY AND ITS PROVIDERS WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS APPLICATION, INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, CONSEQUENTIAL DAMAGES, OR DAMAGES RESULTING FROM THE LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE APPLICATION, ANY DELAYS ON THE APPLICATION, ANY PURCHASE, LICENSE, OR SERVICE RELATED TO THE APPLICATION, OR THE INABILITY TO USE THE APPLICATION, ANY PORTION THEREOF, OR ANY HYPERLINKED OR EMBEDDED APPLICATION, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, EVEN IF DFP SAFETY OR ANY OF ITS PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE TOTAL LIABILITY OF DFP SAFETY AND ITS PROVIDERS, IF ANY, ARISING OUT OF OR IN ANY WAY RELATED TO USE OF ANY OF THE SERVICES OR THIS APPLICATION OR ITS IMPLEMENTATION SHALL NOT EXCEED THE GREATER OF $1.00 OR 50% OF THE FEES PAID BY YOU TO DFP SAFETY UNDER THESE TERMS OF USE AND ANY APPLICABLE PROVIDER TERMS. THIS SHALL BE THE EXCLUSIVE REMEDY HEREUNDER.</li></br>" +
            "<li><strong><u>Indemnification</u></strong>. You hereby agree that you will defend, indemnify, and hold harmless DFP Safety and its Providers from all manners of suit, actions, damages, charges, and expenses, including attorney and counsel fees, which DFP Safety or its Providers may sustain by reason of your use of this Application, your breach of any of the terms, covenants, or conditions of these Terms of Use, or other claims against DFP Safety arising from these Terms of Use.</li></br>" +
            "<li><strong><u>Export Controls</u></strong>. This Application and the Services may only be used in compliance with applicable statutes or regulations relating to the export control laws and regulations of the United States of America and any amendment thereof. You acknowledge that no Services or other underlying information or technology accessed hereunder may be accessed, downloaded, used, possessed, or otherwise exported or re-exported to (or to a national or resident of) any country outside of the United States (including further export if you took delivery of the Services inside the United States) without first complying strictly and fully with all export controls that may be imposed by the United States government or any country or organization of nations within whose jurisdiction you use the Services or other underlying information or technology. If you have any questions regarding its obligations under the United States of America Export Regulations, you should contact legal counsel of your choosing.</li></br>" +
            "<li><strong><u>Third-Party Applications and Providers</u></strong>. This Application may link, redirect, connect, \"frame,\" and otherwise direct you to, without limitation, other Applications, servers, third-party internet data, software or service providers, software developers, internet storefronts, Internet Service Providers, and mobile/wireless communications carriers, among others (<u>Providers</u>). To the extent applicable, these Terms of Use shall apply. In order to utilize some of the DFP Safety Services and services, you may have to use, accept, install, and review information, data, executables, programs, software, and other items from Providers that are not under the control of DFP Safety. This may occur with or without your knowledge and although the visual representation on your screen may appear to be a DFP Safety website, the information, data, executables, programs, software, and other items may come from Providers and may not be under the control of DFP Safety. You acknowledge that DFP Safety is not responsible for the accuracy, copyright, and other intellectual property compliance, legality, decency, or any other aspect of the content of such Providers. Your use of this Application and the products and services through these Providers is at your own risk. DFP Safety is not responsible for webcasting or any other form of transmission received from any linked Application, nor the failure of any services provided through mobile/wireless carriers, internet storefronts, or other Providers. DFP Safety is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by DFP Safety, nor has DFP Safety independently authenticated products or materials provided by Providers.</li></br>" +
            "<li>[<em><strong> <u>Advertisements</u>.</strong> The Application is or may be supported by advertising revenue and may include advertisements for products and services offered by third parties. DFP Safety makes no representations or warranties with respect to the quality, appropriateness, accuracy, truthfulness, reliability, business ethics, or other aspects of any such advertisements or the organizations placing the advertisements and shall have no responsibility or liability for any claims arising out of or related to any such advertisements, the contents thereof, the products or services promoted therein, or the fulfillment thereof. It is a user&rsquo;s sole responsibility to satisfy himself or herself as to the desirability of dealing with any given advertiser and to understand the relationship is between the user and the advertiser and not with DFP Safety. The Application may display political advertising as a business transaction, from advocacy groups and candidates for office. DFP Safety does not endorse candidates for political office or endorse any political statements, positions, or issues.</em>]</li></br>" +
            "<li><strong><u>Parental Control Protections</u></strong><strong>. </strong>DFP Safety has the legal obligation to advise you that parental control protections (such as computer hardware, software, or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors.</li></br>" +
            "<li><strong><u>Privacy</u></strong><strong>.</strong> DFP Safety is committed to safeguarding your privacy online and has established a Privacy Policy to explain to users how their information is collected and used. This Privacy Policy is located at the following web address: http://www.Dewalt.in. Your use of the Application or any of DFP Safety&rsquo;s Services, services, Data, materials, or content signifies your acknowledgement of, and agreement to, DFP Safety&rsquo;s Privacy Policy. DFP Safety reserves the right to modify or amend its Privacy Policy from time-to-time as it deems necessary in its sole discretion.</li></br>" +
            "<li><strong><u>Modifications</u></strong><strong>.</strong> DFP Safety may modify these Terms of Use at any time without notice, and the new terms and conditions will become effective by posting the new terms and conditions in the same location as the previous terms and conditions were posted. DFP Safety has the right at any time to modify or cancel any feature or functionality of the Application, including hours of availability, content, applications, and equipment requirements for use with the Services or services, and DFP Safety reserves the right to suspend or terminate access to this Application or the Services or services or remove any content placed on the Application at any time as DFP Safety deems necessary in its sole discretion.</li></br>" +
            "<li><strong><u>Terms of Service</u></strong><strong>.</strong> These Terms of Use are effective upon your use of the Application and shall remain and continue until terminated by DFP Safety. Neither these Terms of Use nor any rights or obligations hereunder may be assigned by you without the express written permission of DFP Safety, which DFP Safety may withhold in its sole discretion, and any purported transfer of rights shall oblige the transferee to these Terms of Use, and your rights will be terminated. You may terminate these Terms of Use by destroying or removing the Services and all copies thereof, if any, and certifying as such to DFP Safety in whatever form or format requested by DFP Safety. DFP Safety may terminate your right to use the Application and its Services and services as it deems necessary in its sole discretion. Upon such termination by DFP Safety, you agree to certify the destruction, removal, or obliteration of the Services and all copies thereof to DFP Safety in whatever form or format requested by DFP Safety.</li></br>" +
            "<li><strong><u>Notice</u></strong>. Posting of notice on the Application by DFP Safety shall constitute notice to you.</li></br>" +
            "<li><strong><u>Choice of Laws / Jurisdiction</u></strong>. These Terms of Use are governed by the laws of the State of Minnesota, with the exception of export control or other matters of federal question that are governed by the laws of the United States of America. Any dispute arising out of these Terms of Use or related thereto shall be subject to the jurisdiction of the state or federal courts, as applicable, located in Minneapolis, Minnesota and you consent to the personal jurisdiction thereof.</li></br>" +
            "<li><strong><u>LANGUAGE</u></strong>. TO THE EXTENT THESE TERMS OF USE MAY BE TRANSLATED INTO A LANGUAGE OTHER THAN ENGLISH AND THERE IS A CONFLICT OF TERMS BETWEEN THE ENGLISH AND OTHER LANGUAGE VERSIONS, THE ENGLISH VERSION SHALL CONTROL.</li></br>" +
            "<li><strong><u>ENTIRE AGREEMENT</u></strong>. THESE TERMS OF USE, TOGETHER WITH ANY End User License Agreement, PROVIDER TERMS, AND ANY OTHER AGREEMENTS OR TERMS OF USE APPEARING OR REFERENCED ON THIS APPLICATION OR ENTERED INTO BETWEEN THE PARTIES IN WRITING REPRESENT THE ENTIRE SET OF TERMS OF USE GOVERNING YOUR USE OF THE SERVICES (WHERE APPLICABLE) ACCESSED THROUGH THIS APPLICATION, AND IT SUPERSEDES ANY PRIOR PROPOSAL, REPRESENTATION, OR UNDERSTANDING BETWEEN THE PARTIES. THESE TERMS OF USE MAY ONLY BE MODIFIED IN WRITING BY DFP SAFETY.</li>" +
            "</ol>" +
            "<p>Last Modified: August 06, 2022.</p>" +
            "<p><u><strong>DFP Safety Vault Privacy Policy</strong></u></p>" +
            "<p>PLEASE READ THIS PRIVACY POLICY CAREFULLY BEFORE USING THE DFP SAFETY VAULT MOBILE APPLICATION (THE <u>APPLICATION</u>). YOUR ACCEPTANCE OF THIS PRIVACY POLICY GOVERNING YOUR USE OF THE APPLICATION IS A CONDITION OF YOUR RIGHTS TO FURTHER ACCESS ANY AND ALL MATERIALS CONTAINED ON OR ACCESSED THROUGH THE APPLICATION. IF YOU DO NOT AGREE WITH THIS PRIVACY POLICY, PLEASE DO NOT USE THE APPLICATION.</p>" +
            "<ol>" +
            "<li><strong> <u>General</u></strong>. DFP Safety Corporation, a Delaware corporation (referred to herein as &ldquo;<u>DFP Safety</u>,&rdquo; &ldquo;<u>we</u>,&rdquo; &ldquo;<u>us</u>,&rdquo; or &ldquo;<u>our</u>&rdquo;), designs and operates its Application with the goal to protect your privacy and further comply with our Application privacy policy (&ldquo;<u>Privacy Policy</u>&rdquo;). By accessing, receiving, downloading, syncing, using, or possessing or continuing to access, receive, download, sync, use, or possess software, toolbars, user interfaces, applications, and associated media (<u>Software</u>) for use via the Internet, or via wireless or other handheld or mobile devices (<u>Hardware</u>), printed, online, and electronic materials associated therewith (<u>Documentation</u>) and data, materials, and content (<u>Data</u>) (collectively Software, Data, and Documentation to be known as <u>Services</u> herein) submitting a registration form, or clicking the \"I Agree\" or \"Continue\" buttons when prompted and completing the registration form, you are entering into this Agreement with DFP Safety, and you hereby acknowledge and agree to the validity and applicability of the Privacy Policy.</li></br>" +
           
            "<li><strong> <u>General Data Protection Regulation</u></strong>. The General Data Protection Regulation (&ldquo;<u>GDPR</u>&rdquo;) applies to the processing of personal data in the context of the activities of an establishment in the European Economic Area (&ldquo;<u>EEA</u>&rdquo;), as well as to firms outside the EEA that process personal data relating to the offering of services to individuals in the EEA. Please note that certain sections of this Privacy Policy, as identified below, only apply where the GDPR applies to the processing of your personal data.</li></br>" +
            "<li><strong> <u>California Consumers</u></strong>. Effective January 1, 2020, the California Consumer Privacy Act (CCPA) allows California residents, upon a verifiable consumer request, to request that a business that collects personal information from California consumers to give consumers access, in a portable and (if technically feasible) readily usable form, to the specific pieces and categories of personal information that the business has collected about the consumer, the categories of sources for that information, the business or commercial purposes for collecting the information, and the categories of third parties with which the information was shared. California residents also have the right to submit a request for deletion of information under certain circumstances. Please note that you must verify your identity and request before further action is taken.&nbsp; As a part of this process, government identification may be required. Consistent with California law, you may designate an authorized agent to make a request on your behalf. In order to designate an authorized agent to make a request on your behalf, you must provide a valid power of attorney; or the agent must provide proof that you gave the agent signed permission to submit the request and either (i) verify your identity with us or (ii) directly confirm with us that you provided the authorized agent permission to submit the request.</li></br>" +
            "<li><strong> <u>Purpose of Information</u></strong>. We use your personal data to (1) correspond with you, send you information or promotional materials that you have requested through our Application, by email, or telephone request; (2) correspond with third parties such as service providers, legal advisors, auditors, and technology providers and regulatory authorities to comply with any legal obligation imposed on us or in order to pursue our legitimate business interests; (3) maintain our records; and (4) operate the Application and perform the Services, including analyzing your use of our Application.</li></br>" +
            "<li><strong> <u>Information collected</u></strong>. We collect certain identifying information from or about you in connection with your use of the Services, including, without limitation, any information that may be used to identify an individual such as a first and last name, business details, a phone number, or an email address. The purposes for which we may collect, store, and use personal data about you and our &lsquo;lawful basis&rsquo; for processing such data are set out below.</li></br>" +
            "<li><strong> <u>Lawful Basis for Processing</u></strong>. Our basis for processing your data include (1) our legitimate interests in responding to your inquiry, sending you the information you have requested, or otherwise communicating with you in the course of our business; (2) compliance with applicable legal obligations; (3)&nbsp;our legitimate interests in conducting our business in a proper manner; and (4) our legitimate interests in studying how our Application and Services are used, keeping our Application updated and relevant, developing our business and informing our marketing strategy, and where required by law, to do so or if we reasonably believe that it is necessary to protect our rights or to comply with judicial or regulatory proceedings, a court order, or other legal process.</li></br>" +
            "<li><strong> <u>Information Sharing</u></strong>.<strong> </strong>We do not sell, rent, or lease our user lists or the identity of individual users to third parties. DFP Safety does not disclose personal data about its clients to non-affiliated third parties, except as required or permitted by law, for its everyday business purposes (such as to process transactions or service a client account). Under certain circumstances, DFP Safety may also disclose personal information if we become subject to a subpoena or court order, or if we are otherwise legally required to disclose information. We may also use and disclose personal information to establish or exercise our legal rights, to enforce the Terms of Use (the &ldquo;<u>Terms</u>&rdquo;), to assert and defend against legal claims, or if we believe such disclosure is necessary to investigate, prevent, or take other action regarding actual or suspected illegal or fraudulent activities or potential threats to the physical safety or well-being of any person. We share your information with (1) our affiliates or subsidiaries with respect to company performance or for marketing and business development; (2) professional advisers including lawyers, bankers, auditors, and insurers; and (3) regulators and other service providers.</li></br>" +
            "<li><strong> <u>Information Collection</u></strong>.<strong> </strong>We collect personal and non-personal data about you when you provide information to us when communicating or transacting with us in writing by filling in forms or by corresponding with us by mail, telephone, e-mail, or otherwise. As you interact with our Application, we may automatically collect technical data about your equipment, usage of the Application, and patterns. We collect this personal data by using cookies, server logs, and other similar technologies. We adhere to the standards set out in this Privacy Policy and do not monitor or follow any &ldquo;do not track&rdquo; browser requests.</li></br>" +
            "<li><strong> <u>Information Retention</u></strong>.<strong> </strong>We will retain your personal data for as long as necessary to fulfil the purposes for which it was collected, including for the purposes of satisfying any legal, regulatory, accounting, or reporting requirements and our legitimate interests in maintaining such personal information in our records. In doing this we will have regard to the amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorized use or disclosure of your personal data, the purposes for which we process your personal data, and whether we can achieve those purposes through other means and the applicable legal requirements. Generally, we will keep information relevant to our dealings with you for a minimum period of seven years following the last date of activity or longer as required by applicable law or regulation. Once we no longer require your personal data for the purposes for which it was collected, we may securely destroy your personal data in accordance with applicable laws and regulations.</li></br>" +
            "<li><strong> <u>Policy Changes</u></strong>. We may change this Privacy Policy at any time without notice. The most recent version of the Privacy Policy is reflected by the version date located at the bottom of this Privacy Policy. All such updates and amendments are effective immediately upon posting a revised version of this Privacy Policy or other notice on the Application. You should view this Privacy Policy often to stay informed of changes that may affect you. We expressly reserve the right to make any changes to this Privacy Policy at any time, without prior notice to you. The version of this Privacy Policy posted on the Application on each respective date you visit the Application shall be the Privacy Policy applicable to your access and use of the Application on that date.</li></br>" +
            "<li><strong> <u>User Choices</u></strong>.<strong> </strong>When submitting information, corresponding, making requests for information, and otherwise interacting with DFP Safety and its representatives through or in connection with the Application, you choose what information to supply or submit, whether you wish to receive further information, and how you may be contacted. You are not required or obliged to share such information and should only share information that you believe is necessary or appropriate. However, please note that our Application may automatically collect certain technical data.</li></br>" +
            "<li><strong> <u>User Rights</u></strong>. Where the GDPR applies to the processing of your personal data, you have rights as an individual which you can exercise in relation to the information we hold about you under certain circumstances. These rights are to (1) request access to your personal data (commonly known as a &ldquo;data subject access request&rdquo;) and request certain information in relation to its processing; (2) request rectification of your personal data; (3) request the erasure of your personal data; (4) request the restriction of processing of your personal data; (5) object to the processing of your personal data; and (6) request the transfer of your personal data to another party.</li>" +
            "<p>If you want to exercise one of these rights please contact us at support@dfpsafetyvault.com or DFP Safety Corporation, 20711 Holt Ave., #1525, Lakeville MN 55044. You also have the right to make a complaint at any time to a supervisory authority for data protection issues.</p>" +
            "<li><strong> <u>User Requirements</u></strong>. We may need to request specific information from you to help us confirm your identity and ensure your right to access the information (or to exercise any of your other rights). This is another appropriate security measure to ensure that personal data is not disclosed to any person who has no right to receive it.</li></br>" +
            "<li><strong> <u>Information Protection</u></strong>.<strong> </strong>While DFP Safety takes commercially reasonable measures to secure and protect information transmitted via the Application, no security system is impenetrable. We cannot guarantee that information that users of our Application may happen to transmit or otherwise supply will be totally secure. You agree to immediately notify us of any breach of the Application&rsquo;s security, this Privacy Policy, or the Terms of which you become aware.</li></br>" +
            "<li><strong> <u>User-Provided Content</u></strong>. Any information, communications, or material of any type or nature that you submit to the Application by e-mail, posting, messaging, uploading, downloading, or otherwise (collectively, a &ldquo;<u>Submission</u>&rdquo;) is done at your own risk. We cannot control the actions of other users and we are therefore not responsible for any Submissions contained on the Application. By visiting our Application, you are representing and warranting to us that you have reviewed this Privacy Policy and the Terms and that you will abide by all such provisions contained therein.</li></br>" +
            "<li><strong> <u>Visiting the Application from Outside the United States</u></strong>. If you are visiting the Application, or any part thereof, from outside of the United States of America, please be aware that your information may be transferred to, stored, or processed in the United States as our Application is hosted there. The data protection and other laws of the United States and other countries might not be as comprehensive as those in your country, but please be assured that we take steps to protect your privacy. Where this is the case, we will put in place appropriate safeguards such as the EEA-approved standard contractual clauses to ensure that your personal data is treated in a manner that is consistent with and respects the EEA laws on data protection.</li>" +
            "</ol>" +
            "<p>This Privacy Policy was last updated on August 06, 2022.</p>" +
            "</html>";
    String webData_spenish = webData;
    String server_alert = "<html>" +
            "<h3 align=center>&quotBlack Box Application Updation&quot</h3>" +
            "<p>Dear Valued Customer,</p>" +
            "<p>We wish you a Merry Christmas and a Happy New Year, and hope you are safe and doing well in these rather difficult times of COVID.</p>" +
            "<p>Last year had its share of challenges, but the silver lining in those dark clouds was your continuous support. We want to take this opportunity to thank you for using the application and making it successful. There are more than 1300 members using the app and the family is growing rapidly.</p>" +
            "<p>Each day new devices and technologies are emerging. To improve your overall experience in using the application across all devices, it is important that we take some necessary time to do upgrades. We have many new features that have been tested and now need to be uploaded on the App Store and Google Play.</p>" +
            "<p>Since it is traditionally a slow work time this coming week, we plan to shut down the Black Box application temporarily from the 25th to the 31st of December 2020. In that time we plan to add some fantastic new features as part of the upgrade. The Black Box application will be fully functional again by January 1st, 2021.</p>" +
            "<p>Thanks for your understanding and your continuous support.</p>" +
            "<p>Happy holidays to all.</p>" +
            "<p>Dewalt Industries<br />" +
            "20711 Holt Ave., #1525, Lakeville MN 55044<br />" +
            "<a data-saferedirecturl=https://www.google.com/url?q=http://www.Dewalt.in&amp;source=gmail&amp;ust=1609068887192000&amp;usg=AFQjCNEAjuOP360-5-WLX577_ot_tDR8-g href=http://www.Dewalt.in/ target=_blank>www.Dewalt.in</a><br />" +
            "<a href=mailto:dewalt@dewalt.in target=_blank>dewalt@dewalt.in</a></p>" +
            "<p align=center>Copyright 2020. Black Box. All Rights <br/> Reserved.</p>" +
            "</html>";
}
