/*
 * Copyright (c)
 * @website: http://arresto.in/
 * @author: Arresto Solutions Pvt. Ltd.
 * @license: http://arresto.in/
 *
 * The below module/code/specifications belong to Arresto Solutions Pvt. Ltd. solely.
 */

package app.com.arresto.Flavor_Id;

public interface FlavourInfo {
    String Fl_CLIENT_ID = "2072";
    String PACKAGE_NAME = "app.com.snn";
    String APP_ID = "app.com.snn";
    double distance_unit = 1.0;
    String unit_name = "km";
    String date_format = "dd-MM-yyyy hh:mm: a";
    String HOST = "https://arresto.in/connect/";
    String webData = "<html>" +
            "<h3 align=center>TERMS OF USE</h3>" +
            "<ol class=decimal>" +
            "<li class=decimal><u><strong>General Introduction</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>Any use of the website and the mobile application named SNN (hereinafter mobile application referred to as the SNN Applications/ Application<sup>1</sup>), is subject to these Terms of Use.</li>" +
            "<li class=decimal>For the purposes of these Terms of Use, the term 'User' shall mean any person registering/ downloading or using the SNN Application. The term ‘User’ shall mean any person including registered licensee downloading or using the SNN Application after providing the requisite information in order to access the SNN Application. </li>" +
            "<li class=decimal>These Terms of Use are provided in an electronic format as prescribed under the Information Technology Act, 2000, the Rules made thereunder and the amendments regarding documents preserved in electronic format. These Terms of Use will govern the use of SNN Application by the User(s).</li>" +
            "<li class=decimal>Downloading, installing, browsing or otherwise using the SNN Application signifies acceptance of these Terms of Use as well as formal agreement to be legally bound by the same. </li>" +
            "<li class=decimal>These Terms of Use constitute the comprehensive terms and conditions for the use of the SNN Application. Any non-compliance with these Terms of Use may lead to disqualification from using the SNN Application.</li>" +
            "<li class=decimal>All rights to alter these Terms of Use are reserved as it may deem fit in its sole and absolute discretion without any obligation of issuing prior notification. Any major change or revision in these Terms of Use will be communicated to the User along with the date when the modification was made.</li>" +
            "<li class=decimal>This document is an electronic record generated by a computer system and does not require any physical or digital signatures.</li>" +
            "<li class=decimal>Any changes made to these Terms of Use will be effective immediately and any continued use of the SNN Application after such change constitutes acceptance of such changes.</li>" +
            "<li class=decimal>In order to use the SNN Application, agreement to these Terms of Use is the first step. The Terms of Use can be accepted by simply clicking on the space provided adjacent to I Agree to Terms & Conditions.</li>" +
            "<li class=decimal>The SNN Application must not be used in any manner or case where there is non-acceptance of these Terms of Use or inability to be bound by them." +
            "</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Registration Process</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The User shall be entitled to use the SNN Application by registering on the SNN Application after furnishing all relevant information as sought. The User who chooses to register on the SNN Application and provide the requisite details, shall be responsible for maintaining the confidentiality of its username and password.</li>" +
            "<li class=decimal>On successful registration, the User will be able to access his/her own account by using the username and password chosen during the registration process. The User(s) shall be responsible for all activities that occur through his/her username and password.</li>" +
            "<li class=decimal>Further, the User agrees, inter alia, to: " +
            "<ol type=i>" +
            "<li>Provide true, accurate, current and complete information as prompted by the SNN Application’s registration form while registering (such information being the Registration data);</li>" +
            "<li>Maintain and promptly update the Registration data to keep it true, accurate, current and complete at all times;</li>" +
            "<li>Immediately notifying the SNN Application of any unauthorized use of password or account or any other actual or suspected breach of security; and</li>" +
            "<li>Ensure logging out from account at the end of each session.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal>For the purposes of these Terms of Use, the term ‘Personally Identifiable Information’ or ‘PII’ shall mean and include any information or set of information, whether alone or in combination with other personal information gathered, processed, used or stored which is sufficient to identify an individual.</li>" +
            "<li class=decimal>In relation to any PII being saved or processed, shall meet the requirements of Information Technology Law and shall adopt the technical and organizational measures as industry standards which are necessary to secure the PII of the User.</li>" +
            "<li class=decimal>As the first step of the Registration process, the SNN Application may require the following PII to be provided, including without limitation to: " +
            "<ul>" +
            "<li>Name (First and Last name);</li>" +
            "<li>Email address;</li>" +
            "<li>Mobile number;</li>" +
            "<li>Username;</li>" +
            "<li>Address;</li>" +
            "<li>Country;</li>" +
            "<li>Province state;</li>" +
            "<li>City;</li>" +
            "<li>Company Name;</li>" +
            "<li>Company Address;</li>" +
            "</ul></li>" +
            "<p>Upon collection, the above-mentioned information shall be subject to the Privacy Policy of the SNN Application.</p>" +
            "<li class=decimal>The User(s) shall be individually responsible for the accuracy and correctness of all such details/information provided during registration on the SNN Application. If there is a reason to doubt the correctness of any details/information furnished or in case any information furnished is found to be incorrect, false or misleading in nature or otherwise not in accordance with these Terms of Use, then the account of the User(s) may be subject to cancellation or indefinite suspension or access to the same may be blocked/ refused.</li>" +
            "<li class=decimal>The providers of the SNN Application shall not be liable for any loss or damage arising from failure of the User(s) to comply with these Terms of Use. The providers of the SNN Application shall not be liable for any unauthorized hacking of the SNN Application leading to leakage and misuse of PII.</li>" +
            "<li class=decimal>The User shall not-" +
            "<ol type=i>" +
            "<li>Select a username, mobile number, email address or any other personally identifiable information of any other person with the intent to impersonate that person; or </li>" +
            "<li>Use a name or contact details subject to any rights of any other person without appropriate authorization. </li></ol>" +
            "<p>In case a User does not adhere to the above conditions, the providers of the SNN Application reserve the right to refuse registration of or cancel registration of such User in its discretion.</p>" +
            "</li>" +
            "<li class=decimal>Internet Carrier charges levied for the use of the SNN Application shall be borne by the User(s) himself/ herself.</li>" +
            "<li class=decimal>The providers of the SNN Application do not levy any registration fees for the purpose of registration on the SNN Application nor does not charge any fee for use of the SNN Application, however, The providers of the SNN Application reserve the right to levy fee for specific service provided as per the request of the User.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Eligibility Criteria</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>Before making any use of SNN Application, User(s) hereby represents and warrants of being at least eighteen (18) years of age or above and being fully able and competent as defined under the provisions of the Indian Contract Act, 1872 to understand and agree the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use. In case the User(s) who are below the age of eighteen (18) years wish to use the SNN Application, then such use shall be under the direct supervision of the legal guardian or parents of the User, who have agreed to these Terms of Use on behalf of such User. In the event a minor uses the SNN Application, it is assumed that he/she has obtained the consent of the legal guardian or parents and such use is made available by his/ her legal guardian or parents. The providers of the SNN Application will not be responsible for any consequence that arises as a result of misuse of any kind of the SNN Application that may occur by virtue of any person including a minor registering for using the SNN Application.</li>" +
            "<li class=decimal>The providers of the SNN Application reserve the right to terminate a User account and / or refuse to provide a User(s) with access to the SNN Application if it is discovered that such User(s) is under 18 years of age and his/ her parent/legal guardian do not consent to use of SNN Application or if any information provided by the User(s) is inaccurate.</li>" +
            "<li class=decimal>It is agreed that the providers of the SNN Application do not have the responsibility to ensure that User conforms to the aforesaid eligibility criteria. Any person under the age of 18 years should seek the consent of their parents/legal guardians before providing any information about himself/ herself or his/ her parents/ legal guardian on the SNN Application.</li>" +
            "<li class=decimal>Only those Users which comply with all laws and regulations in force shall be eligible to register with the SNN Application, and the SNN Application shall be used only in compliance with these Terms of Use in a manner that does not violate the legal rights of the providers of the SNN Application.</li>" +
            "</ol> " +
            "</li>" +
            "<li class=decimal><u><strong>Privacy Policy</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The providers of the SNN Application shall be committed to ensuring that the information furnished, as a part of registration process mentioned above, is secure and no unauthorized access or disclosure takes place with respect to the same. The providers of the SNN Application have installed internal checks and mechanisms to ensure the same.</li> " +
            "<li class=decimal>Purpose of collecting PII: The major purposes for the collection of PII are listed below: " +
            "<ol type=i>" +
            "<li>For improving services offered and received using the SNN Application;</li>" +
            "<li>For keeping internal records;</li>" +
            "<li>For market research purposes;</li>" +
            "<li>For the purpose of enhancing User's experience.</li>" +
            "</ol>" +
            "<li class=decimal>In case a User changes his/ her mind and wishes to discontinue sharing his/ her PII, he/ she/ it may express such intention by mailing <mailto:contacto@i4t.cl.>contacto@i4t.cl.</mailto:></li>" +
            "<li class=decimal>The providers of the SNN Application reserve the right at all times to disclose any information as may be required by law. This may include disclosure of information for investigation of an alleged illegal activity or its response to a lawful court order.</li>" +
            "<p>To know more about the Company's policy on collection and use of data, please go through our Privacy Policy.</p>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Prohibited Use</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The Users shall use the SNN Application solely for personal and non-commercial purposes.</li> " +
            "<li class=decimal>The Users shall not decompile, reverse engineer, or disassemble the contents of the SNN Application or modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information obtained from the use of SNN Application. </li>" +
            "<li class=decimal>The User shall not use the SNN Application in any way that is unlawful or harms the goodwill or reputation of the providers of the SNN Application. </li> " +
            "<li class=decimal>The User shall not use the SNN Application in any way which:" +
            "<ol type=i>" +
            "<li>Interferes with another person’s use of the SNN Application;</li>" +
            "<li>Makes or transmits electronic copies of materials protected by copyright without the permission of the owner, committing any act that amounts to the infringement of intellectual property or making available any material that infringes any intellectual property rights or other proprietary rights of anyone else;</li>" +
            "<li>Transmits or makes available any material that contains viruses, trojan horses, worms, spyware, time bombs, cancelbots, or other computer programming routines, code, files or such other programs that may harm the SNN Application, interests or rights of other User(s) or limit the functionality of any computer software, hardware or telecommunications;</li>" +
            "<li>Uses the SNN Application in any manner that could damage, disable, overburden or impair any of the servers or the networks connected to any of the servers on which the SNN Application is hosted;</li>" +
            "<li>Use the SNN Application for purposes that are not permitted by these Terms of Use or any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdiction.</li>" +
            "</ol>" +
            "</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Access</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The User’s access to the SNN Application may be occasionally suspended or restricted for the purpose of repairs, maintenance, or the introduction of new facilities or services at any time without prior notice.</li>" +
            "<li class=decimal>There is no warranty, representation or guarantee that the SNN Application, or the use thereof will be uninterrupted, complete, accurate, current, reliable, error-free, secure, or that any problems will be corrected, or that any information, software or other material accessible from the SNN Application is free from viruses or other harmful components.</li>" +
            "<li class=decimal>The providers of the SNN Application do not warrant, guarantee or make any representation regarding the use of or the results arising from the use of the SNN Application either in terms of its compatibility with hardware or other software or equipment, and the User must assume all responsibility and risk for use of the SNN Application its services, information.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Breach</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>Without limiting other remedies, the providers of the SNN Application may, at their sole discretion may limit activity of the User, immediately for temporary/ indefinite period or may suspend or terminate or block membership and/or refuse to provide access to the SNN Application in the event, including but not limited to: " +
            "<ol type=a>" +
            "<li>Breach of the Terms of Use or any other rules and policies as displayed on the SNN Application;</li>" +
            "<li>If the providers of the SNN Application are unable to verify or authenticate the information furnished by the User;</li>" +
            "<li>In such circumstances wherein the providers of the SNN Application are of the opinion that there is a violation of any law(s) in force.</li>" +
            "</ol></li>" +
            "<li class=decimal>The User(s) willing to use the SNN Application also agrees that any breach of these Terms of Use or any other rules or policy as displayed on the SNN Application will constitute an unlawful and unfair business practice, and will cause irreparable harm to the providers of the SNN Application, for which monetary damages would normally be inadequate. In case payment of monetary damages is deemed adequate remedy in the opinion of the providers of the SNN Application, the User(s) consents to pay the same to the providers of the SNN Application , which shall not forestall the obtaining of any injunctive or equitable relief that the providers of the SNN Application deem necessary or appropriate in such circumstances. These remedies shall be in addition to any other remedies the providers of the SNN Application may have in law or in equity.</li>" +
            "<li class=decimal>If the providers of the SNN Application initiate any legal action as a result of any breach of these Terms of Use or any other rules or policy, the providers of the SNN Application shall also be entitled to recover all reasonable legal costs in respect of such action, in addition to any other relief available to them under law.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Intellectual Property Rights</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>Intellectual Property of the providers of the SNN Application remains with the providers which includes, but is not limited to, innovations, improvements, processes, technical know-how, techniques, source code of the providers of the SNN Application, content made literary and artistic works, schematics, patents, proposed trade secrets, its trademarks, trade names, designs, patents and copyrighted works, notes, agreements/ contracts entered by the providers of the SNN Application, formulas, in-house software, VPN etc.. providers of the SNN Application reserve the right to take any legal recourse available for the protection of its Intellectual Property.</li>" +
            "<li class=decimal>All intellectual property rights including trademarks, & copyright of the SNN Application and the SNN Application shall vest in all the providers. It is clarified that the ownership in intellectual property rights pertaining to the SNN Application developed by the content developer shall vest with the content developer and the User shall not indulge in any act that construes such infringement of the intellectual property of the providers of the SNN Application.</li>" +
            "<li class=decimal>User shall not use, receive or copy any source code and look and feel of the SNN Application and shall not reverse engineer, disassemble or decompile, or otherwise attempt to derive source code of the SNN Application for any purpose whatsoever. </li>" +
            "<li class=decimal>Access or use of the SNN Application does not confer and shall not be construed as conferring upon anyone the license to use the Intellectual Property Rights of the providers of the SNN Application.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Posting of Content</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The providers of the SNN Application enable their User(s) to post messages, photographs and video in a various segment as may be desired by User(s) depending on the area, city, state or country the Users in their respective segments will receive the concerned User’s post.</li>" +
            "<li class=decimal>All posts, pictures, photographs, data and any other content (hereinafter referred to as Content), whether publicly posted or privately transmitted, is the sole responsibility of the User and the person who originated such Content. </li>" +
            "<li class=decimal>The User shall be solely responsible for all the Content posted from his/ her account and all activities carried on from his/ her account. The providers of the SNN Application shall take all reasonable steps for the protection of Content added to its cloud server by the User from the use of his/ her account.</li>" +
            "<li class=decimal>The providers of the SNN Application are under no obligation to monitor or control the Content posted on the SNN Application and, the providers of the SNN Application cannot take responsibility of the correctness and accuracy of such Content. Any use or reliance on any Content or materials posted on the SNN Application or obtained by the User on the SNN Application is at the User’s own risk and prudence. </li>" +
            "<li class=decimal>The providers of the SNN Application do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any Content or communications posted on the SNN Application or endorse any opinions expressed on the SNN Application.</li>" +
            "<li class=decimal>The User understands that by using the SNN Application, the User may be exposed to Content that might be offensive, harmful, inaccurate or otherwise inappropriate, or in some cases, Content that have been mislabeled or are otherwise deceptive. Under no circumstances will the providers of the SNN Application be liable in any way for any Content whatsoever, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available on the SNN Application.</li>" +
            "<li class=decimal>The providers of the SNN Application reserve the right to modify or adapt the User’s Content in order to transmit, display or distribute it over computer networks and in various media and/or make changes to the Content as are necessary to conform and adapt that Content to any requirements or limitations of any networks, devices, services or media.</li>" +
            "<li class=decimal>The User agrees that he/she is responsible for use of the SNN Application, for any Content provided, and for any consequences thereof, including the use of Content by other users and third-party associates of the providers of the SNN Application.</li>" +
            "<li class=decimal>The User represents and warrants that you have all the rights, power and authority necessary to grant the rights granted herein to any Content that you submit.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Termination/Deletion of Account</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The User is solely responsible for properly deleting his/ her account, by sending an email to <mailto:contacto@i4t.cl.>contacto@i4t.cl.</mailto:></li>" +
            "<li class=decimal>All of the User’s content will immediately be inaccessible from the SNN Application upon deletion. Within 30 days, all this content will be permanently deleted from all backups and logs. This information cannot be recovered once it has been permanently deleted.</li>" +
            "<li class=decimal>The providers of the SNN Application, in their sole discretion, has the right to suspend or terminate the User’s account in case of prolonged inactivity or misuse of the SNN Application which is a violation of any provision(s) of these Terms of Use or violation of any applicable law. Such termination will result in the deactivation or deletion of the User’s account or access to the account, and the forfeiture and relinquishment of all Content in the account. The providers of the SNN Application reserve the right to refuse service to anyone for any reason at any time. </li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Right to monitor the content</strong></u>" +
            "<p>The providers of the SNN Application reserve the right to monitor the Content available on the SNN Application whether made available by itself or by any User.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>Indemnification</strong></u>" +
            "<p>The User agrees to indemnify, defend and hold harmless the providers of the SNN Application, and their affiliates and their officers, directors, employees, contractors, agents, licensors, service providers, subcontractors and suppliers from and against any and all losses, liabilities, expenses, damages and costs, including reasonable attorneys' fees and court costs, arising or resulting from the use of the SNN Application and any violation of these Terms of Use or any applicable law.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>Limitation of Liability</strong></u>" +
            "<p>To the fullest extent permitted by applicable laws, in no event shall the providers of the SNN Application be liable for any damages resulting from any of the following:</p>" +
            "<ol type=i>" +
            "<li>errors, mistakes, or inaccuracies of content;</li>" +
            "<li>personal injury or property damage, of any nature whatsoever, resulting from access to and use of the Services including the SNN Application;</li>" +
            "<li>any unauthorized access to or use of our servers and/or any and all PII stored therein;</li>" +
            "<li>any interruption or cessation of transmission to or from our servers;</li>" +
            "<li>any bugs, viruses, Trojan horses, or the like, which may be transmitted to or through the services by any third party;</li>" +
            "<li>any loss of data or content;</li>" +
            "<li>any errors or omissions in any content or for any loss or damage of any kind incurred as a result of the Users utilizing of any content posted, transmitted, or otherwise made available via the SNN Application, whether based on warranty, contract, tort, or any other legal theory;</li>" +
            "<li>the disclosure of information pursuant to these terms or our Privacy Policy;</li>" +
            "<li>The User’s failure to keep the password or account details secure and confidential;</li>" +
            "<li>In no event shall the providers of the SNN Application or any indirect, incidental, special, punitive, exemplary or consequential damages whatsoever, however caused and under any theory of liability, including but not limited to, any loss of profit (whether incurred directly or indirectly), any loss of goodwill or business reputation, any loss of data suffered, cost of procurement of substitute goods or services, or other intangible loss.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Force Majeure</strong></u>" +
            "<p>The term force majeure shall include, but not be limited to fires, floods, acts of God or the public enemy, embargoes, wars (declared or undeclared), riots, civil commotion, interference by civil or military authorities, terrorist acts, Government actions, order(s) or request (s), including (without limitation) certification, clearance or other document, or any other cause or contingency beyond the control of the providers of the SNN Application in any of the aforesaid events.</p>" +
            "<p>The providers of the SNN Application shall not be liable for failure to perform or any delay in performance of services when and to extent that such failure or delay is due to force majeure." +
            "</p>" +
            "</li>" +
            "<li class=decimal><u><strong>Dispute Resolution</strong></u>" +
            "<ol type=a>" +
            "<li>Where any dispute or disagreement arises between the providers of the SNN Application and the User as to the interpretation or application of any of the terms, conditions, requirements or obligations under these Terms of Use or use of the SNN Application, such dispute or disagreement shall be amicably resolved vide mutual discussions. </li>" +
            "<li>In cases of failure to resolve the dispute/ disagreement resolved within 30 days of such discussions the dispute shall be referred to and finally resolved by the laws in force." +
            "</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>Governing Law and Jurisdiction</strong></u>" +
            "<p>These Terms of Use shall be governed by the laws of Republic of India and the User(s) willing to utilize the <b>SNN Application</b> hereby consents to the exclusive jurisdiction of courts in India in all disputes arising out of or relating to the use of the <b>SNN Application</b>. Use of the <b>SNN Application</b> is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms of Use, including but without limitation to this paragraph. </p>" +
            "</li>" +
            "<li class=decimal><u><strong>Severability</strong></u>" +
            "<p>If any of the provisions of this Agreement or part thereof is rendered void, illegal or unenforceable in any respect under any law, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby</p>" +
            "</li>" +
            "<li class=decimal><u><strong>Headings</strong></u>" +
            "<p>Headings of the sections of these Terms of Use are inserted for convenience reasons only and shall not constitute a part hereof or affect in any way the meaning or interpretation of the content of the respective sections.</p>" +
            "</li>" +
            "<u><sup>1</sup> developed by Arresto Solutions Pvt. Ltd. </u>" +
            "<br>" +
            "</ol>" +
            "<h3>PRIVACY POLICY</h3>" +
            "<ol class=decimal>" +
            "<li class=decimal><u><strong>PURPOSE</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The website and/ mobile application SNN (hereinafter referred jointly referred to as the SNN Application/ Application) made available by Visca Safety Comercial Limitada (hereinafter referred to as providers of the SNN Application <sup>1</sup>) is committed to protecting the privacy rights of its user(s) and recognizes the need for appropriate protection and management of any Personally Identifiable Information (hereinafter referred to as PII) and the services provided at the request of the person using the SNN Application (hereinafter referred to Services). </li>" +
            "<li class=decimal>For the purposes of the provisions under this Privacy Policy, the term 'User' shall mean any persons who use the SNN Application and/or register themselves through the SNN Application after providing the information as requested in order to avail the Services.</li>" +
            "<li class=decimal>This Privacy Policy explains the policy of the providers of the SNN Application regarding the collection, use, disclosure and transfer of the User's personally identification information in relation with the use of the SNN Application including but not limited to delivery of information and content. </li>" +
            "<li class=decimal>This Privacy Policy forms part and parcel of the Terms of Use for the use of SNN Application and the effective date when this Privacy Policy comes into force will be the date when the User first uses the SNN Application.</li>" +
            "<li class=decimal>This Privacy Policy is embedded in an electronic format under the Information Technology Act, 2000 and the Rules made thereunder and the amendments regarding electronic documents as amended by the said act. There is no requirement of any physical, electronic or digital signature on this Privacy Policy.</li>" +
            "<li class=decimal>As used in this Policy, Personally Identifiable Information or PIIshall mean and include any information that alone or in combination with other information relates to a specific, identifiable individual person. By way of illustration and not limitation, PII includes individuals' names, personal identification numbers such as UIDAI No., PAN no. etc., an individual's mobile number, home or office telephone number, email address, home or office address, age, occupation, location, height, weight, birth date and any other information provided by the User which is of personally identifiable form. </li>" +
            "<sup>1</sup> developed by Arresto Solutions Pvt. Ltd." +
            "<li class=decimal>This Privacy Policy applies to all PII collected by the providers of the SNN Application during the course of any usage of the service provided. By using the Service, the User agrees to comply with policies of the the SNN Application. The Privacy Policy is designed to assist the User in understanding how PII is being collected and assisting them in making informed decisions while using the SNN Application.</li>" +
            "<li class=decimal>Downloading, installing, browsing or otherwise using the SNN Application signifies acceptance of these Privacy Policy as well as formal agreement to be legally bound by the same. Any changes made to these Privacy Policy will be effective immediately and any continued use of the SNN Application after such change constitutes acceptance of such changes.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>COLLECTED INFORMATION:</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>Users who use and/or register on the SNN Application will be requested to provide their PII. The PII is used for efficient service and better user experience for the User.</li> " +
            "<li class=decimal>By accessing the SNN Application or otherwise using the Services, the User consents to collection, storage, and use of the PII provided by him/her (including any changes thereto as provided) to avail any of the Services that the providers of the SNN Application offer. </li>" +
            "<li class=decimal>The providers of the SNN Application may enter into agreements with third parties to store or process information/ data of Users. These third parties may have their own security standards to safeguard the information or data of Users and the providers of the SNN Application will on a commercially reasonable basis require from such third parties to adopt reasonable security standards to safeguard information / data of Users.</li>" +
            "<li class=decimal>The providers of the SNN Application respect the privacy of the Users and are committed to reasonably protect it in all respects. The types of information about the User which may be collected by the providers of the SNN Application are as follows:</li>" +
            "<ol type=i>" +
            "<li>Information supplied by Users</li>" +
            "<li>Information automatically tracked while navigating the application</li>" +
            "<li>Information collected from any other source (collectively referred to as Information)</li></ol></br>" +
            "<b><u>Information supplied by Users</u></b>" +
            "<p>While signing up on the SNN Application and accessing the SNN Application, the application form collects the information, including but not limited to:</p>" +
            "<ul>" +
            "<li>Contact Information (e.g., name, email address, phone number, billing or mailing address)</li>" +
            "<li>Account information</li>" +
            "<li>IP address, geolocation</li>" +
            "<li>Identity validation (e.g., photograph, other information requested to verify your information)</li>" +
            "<li>National identification numbers</li>" +
            "<li>Date of birth</li>" +
            "<li>Details of any transactions carried out using any of the Services</li>" +
            "<li>Any other information that the User chooses to provide to us (e.g., by sending an email/otherwise contact us)</li>" +
            "<li>Calls/emails/other correspondence</li>" +
            "<li>Payment and Banking Information</li>" +
            "</ul></li>" +
            "</ul></li>" +
            "</ol>" +
            "</li>" +
            "<u><strong>INFORMATION AUTOMATICALLY TRACKED WHILE NAVIGATION</strong></u>" +
            "<p>THE PROVIDERS OF THE SNN APPLICATION MAY ALSO COLLECT INFORMATION THROUGH THE USER'S INTERACTION WITH AND USE OF THE SNN APPLICATION WHICH DOES NOT REVEAL THE USER'S SPECIFIC IDENTITY OR DOES NOT DIRECTLY RELATE TO AN INDIVIDUAL. SUCH INFORMATION MAY INCLUDE, BUT IS NOT LIMITED TO, BROWSER AND DEVICE INFORMATION, DATA COLLECTED THROUGH AUTOMATED ELECTRONIC INTERACTIONS, SNN APPLICATION USAGE DATA, DEMOGRAPHIC INFORMATION, GEOGRAPHIC OR GEO-LOCATION INFORMATION, STATISTICAL AND AGGREGATED INFORMATION. </p>" +
            "<u><strong>INFORMATION COLLECTED FROM ANY OTHER SOURCE</strong></u>" +
            "<p>THE PROVIDERS OF THE SNN APPLICATION MAY RECEIVE INFORMATION ABOUT THE USER FROM OTHER PUBLIC SOURCES, ADD IT TO THE USER ACCOUNT INFORMATION AND TREAT IT IN ACCORDANCE WITH THIS POLICY. IF THE USER PROVIDES INFORMATION TO THE PLATFORM PROVIDER OR OTHER PARTNER, WHOM THE SERVICES ARE PROVIDED, THE USER'S ACCOUNT INFORMATION AND ORDER INFORMATION MAY BE PASSED ON TO THE PROVIDERS OF THE SNN APPLICATION. THE PROVIDERS OF THE SNN APPLICATION AND THEIR CONTENT DEVELOPER MAY OBTAIN UPDATED CONTACT INFORMATION AVAILABLE IN PUBLIC DOMAIN FROM THIRD PARTIES IN ORDER TO CORRECT RECORDS AND PROVIDE THE SERVICES OR TO COMMUNICATE WITH THE USER. </p>" +
            "</li>" +
            "<li class=decimal><u><strong>Use of PII</strong></u>" +
            "<ol class=decimal>" +
            "<li class=decimal>The PII of the User(s) may be used to set up and administer the User's account, provide necessary technical support, verify identity of User(s) and send important communication. </li>" +
            "<li class=decimal>The PII of the User(s) excluding pictures, videos and contact details may be used to deliver advertising, marketing and event-based communication. Such communication may contain option to opt out of receiving such communications in future. If the User choses to opt out of receiving such marketing and event-based communication by emailing at contacto@i4t.cl, then the providers of the SNN Application shall not contact such User and will ensure that new data collected about the User(s) from then on will not be used by the providers of the SNN Application for any targeted advertising purposes. However, the providers of the SNN Application may use existing information of the User(s) to customize the SNN Application accordingly.</li>" +
            "<li class=decimal>The providers of the SNN Application may use the PII of the User(s) for internal and external research and development purposes and to improve and test the features and functions of the SNN Application for giving the best options to the Users.</li>" +
            "<li class=decimal>Such important information may include financial data, and legal documents etc. Such information is only made accessible to those User(s) or customers authorized by its respective customer or user. The access to this information is limited to authorized personnel with a critical business reason, such as technical support.</li>" +
            "<li class=decimal>The providers of the SNN Application may use and retain the PII of the User(s) for legal and compliance reasons, such as the prevention, detection, or investigation of a crime; loss prevention; fraud, or to meet our internal and external audit requirements, information security purposes, and or which is required (a) under applicable law (b) to respond to requests from courts, law enforcement agencies, regulatory agencies, and other public and government authorities, (c) to enforce the Terms And Conditions; and (d) to protect the rights, privacy, safety, or property of the providers of the SNN Application.</li>" +
            "<li class=decimal>The providers of the SNN Application do not sell information about its Users to any person or entity whatsoever. However, during development of its business, the providers of the SNN Application may sell or buy companies or assets. In such transactions, customer or user information may be transferred to such companies or assets.</li>" +
            "<li class=decimal>The providers of the SNN Application may also use the PII of the User(s) collected for the following purposes:" +
            "<ol type=i>" +
            "<li>To facilitate various programs and initiatives launched by the providers of the SNN Application or third-party service providers and business associates;</li>" +
            "<li>To analyze how the Services are used, to measure the effectiveness of advertisements, to facilitating payments;</li>" +
            "<li>To protect the integrity of the SNN Application;</li>" +
            "<li>To conduct analytical studies on various aspects including user behavior, user preferences etc.;</li>" +
            "<li>To determine any security breaches, computer contaminant or computer virus; </li>" +
            "<li>To investigate, prevent, or take action regarding illegal activities and suspected fraud;</li>" +
            "<li>To undertake forensics of the concerned computer resource as a part of investigation or internal audit;</li>" +
            "<li>To enhance ability of the providers of the SNN Application to communicate with Users and customers about additional valuable services; </li>" +
            "<li>To ensure fulfillment of a Contract;</li>" +
            "<li>to trace computer resources or any person who may have contravened, or is suspected of having or being likely to contravene, any provision of law including the Information Technology Act, 2000 that is likely to have an adverse impact on the services provided on the SNN Application or by the providers of the SNN Application .</li>" +
            "<li>To provide technical assistances requiring initial setup, support services or dealing with any suspicious activities from the user accounts.</li>" +
            "</ol>" +
            "</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>SHARING OF INFORMATION</strong></u>" +
            "<p>The providers of the SNN Application may share User information with third parties, including service providers, regulated institutions), affiliated entities, payment processing service providers and business partners for the following purposes:</p>" +
            "<ol class=decimal>" +
            "<li class=decimal>Information may be shared with the service providers and affiliates of the providers of the SNN Application to assist in provision of Services and everyday business purpose.</li>" +
            "<li class=decimal>Information may be shared with fraud prevention and detection service providers for the purpose of detecting and preventing fraudulent activity.</li>" +
            "<li class=decimal>Information may be shared with customers, clients or third parties using the Services to perform the Services and assist in carrying out transaction with such parties. </li>" +
            "<li class=decimal>Information may be shared if the providers of the SNN Application believe it necessary to disclose information to investigate, prevent or take action regarding illegal activities, suspend fraud, violations of Terms of Use or this Privacy Policy. </li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>COOKIES</strong></u>" +
            "<p>The providers of the SNN Application may use cookies to operate and provide Services, to improve experiences of the User(s), understand how services are being used, and customize services as per the User's needs and choices. Additionally, cookies may be used to remember choices, such as language preferences, and otherwise to customize services for the User. </p>" +
            "<p>A cookie in no way gives the providers of the SNN Application access to the User's computer or any information about them, other than the data they choose to share with the providers of the SNN Application. The User(s) can choose to accept or decline cookies.</p>" +
            "<p>The helpportion of the toolbar on most browsers will tell the Users how to prevent their browser from accepting new cookies, how to have the browser notify then when they receive a new cookie, or how to disable cookies altogether. However, cookies will allow Users to take full advantage of some of the SNN Application features and it is recommended to leave them turned on. </p>" +
            "</li>" +
            "<li class=decimal><u><strong>LOG FILES</strong></u>" +
            "<p>The providers of the SNN Application maintain log files of the traffic that visits the Service. The providers of the SNN Application do not link any information gathered in these log files to PII. Log files are used to manage traffic loads and information technology requirements for providing reliable service.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>THIRD PARTY LINKS</strong></u>" +
            "<p>The SNN Application also includes links to other websites. Such websites are governed by their respective privacy policies, which are beyond the control of the providers of the SNN Application. Once the User leaves the servers of the providers of the SNN Application, use of any information provided by the User is governed by the privacy policy of the operator of the site which the User is visiting. That policy may differ from that of the providers of the SNN Application. If the User can't find the privacy policy of any of these sites via a link from the concerned third party's website, the User may contact the concerned third party directly for more information. The providers of the SNN Application is not responsible for the privacy practices or the content of such websites.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>INFORMATION SECURITY</strong></u>" +
            "<p>The security of PII is important to the providers of the SNN Application. The providers of the SNN Application follow generally accepted industry standards to protect the PII submitted by User(s). However, no method of transmission over the Internet or method of electronic storage can be said to be 100% secure, therefore, while it is attempted to use commercially acceptable means to protect PII, there is no guarantee of absolute security. </p>" +
            "<p>The User(s) is responsible for all uses of his/her username and password created at the time of signing up on the SNN Application. Please contact the providers of the SNN Application immediately if the User(s) believes password has been misused. The Users shall be individually responsible for maintaining the confidentiality of their username and password and for all activities occurring under their account. The providers of the SNN Application shall not be liable for any misuse or unauthorized use of username and password of the User(s).</p>" +
            "</li>" +
            "<li class=decimal><u><strong>RETENTION OF INFORMATION</strong></u>" +
            "<p>The PII of the User(s) will be kept by the providers of the SNN Application for as long it is necessary to fulfil the purpose for which it was collected, or as required or permitted by applicable laws. The providers of the SNN Application will cease to retain PII of users, or remove the means by which the data can be associated with Users, as soon as it is reasonable to assume that such retention no longer serves the purpose for which the personal data was collected, and is no longer necessary for legal or business purposes. The providers of the SNN Application shall at all times assume that the information provided by the User(s) is correct, genuine and updated. The providers of the SNN Application shall not be held liable for any false/ incorrect information/ data of the User/s. The User shall indemnify the providers of the SNN Application in case of any loss, damage or injury caused to it due to the use or lawful disclosure of false data provided by the User(s).</p>" +
            "</li>" +
            "<li class=decimal><u><strong>SPAMMING</strong></u>" +
            "<p>It is contrary to this policy for User(s) to use the SNN Application to effect or participate in any of the following activities:</p>" +
            "<ol class=decimal>" +
            "<li class=decimal>To send unsolicited mass e-mailings, whether or not such unsolicited e-mailings provoke complaints from the recipients;</li>" +
            "<li class=decimal>To engage in any of the foregoing activities using the service of another provider, but channeling such activities through the Services. </li>" +
            "<li class=decimal>To falsify User(s) information provided in the SNN Application or to other User(s) of the Service in connection with use of the Service.</li>" +
            "</ol>" +
            "</li>" +
            "<li class=decimal><u><strong>THIRD PARTY DISCLOSURES</strong></u>" +
            "<p>The providers of the SNN Application do not sell, trade, lend, transfer or disclose any PII collected from the User(s) to third parties except as set forth in this Privacy Policy. However, the providers of the SNN Application reserve the right to provide the PII to its employees or partners or agents who have a need-to-know such information for the purpose of maintenance and development of the SNN Application and enabling the providers of the SNN Application to provide Services to the User(s). However, this does not include trusted third parties such as contractors and vendors who assist the providers of the SNN Application in operating the Service, conducting business, or servicing the users, so long as those parties agree to keep this information confidential. </p>" +
            "<p>The providers of the SNN Application also reserves the right to disclose PII when special circumstances call for it, such as when disclosure is required by law or court order or when disclosure is, in the sole discretion of the providers of the SNN Application, necessary to protect legal rights, including intellectual property rights." +
            "</p>" +
            "</li>" +
            "<li class=decimal><u><strong>VIOLATION OF THE POLICY</strong></u>" +
            "<p>Upon becoming aware of an alleged violation of this Policy or Terms of Use, the providers of the SNN Application may initiate an investigation. During the investigation, the User's access to the Service may be suspended, restricted or limited in order to prevent further unauthorized activities. Depending on the severity of the violation, the providers of the SNN Application may, at its sole discretion, restrict, suspend, or terminate User's account and pursue other civil remedies. If such violation is a criminal offence the providers of the SNN Application will notify the appropriate Government authority of such violation.</p>" +
            "</li>" +

            "<li class=decimal><u><strong>CONSENT</strong></u>" +
            "<p>The User consents to the collection and use of his/ her PII as described in this Privacy Policy. </p>" +
            "</li>" +
            "<li class=decimal><u><strong>CONTACT</strong></u>" +
            "<p>The providers of the SNN Application have appointed an internal data protection officer for the Users to contact if a User has any queries, clarifications or complaints regarding compliance with this Policy or relating to processing of information. The data protection officer's name and contact information are provided below:</p>" +
            "Name: Visca Safety Comercial Limitada<br>" +
            "Email id: <mailto:contacto@i4t.cl>contacto@i4t.cl</mailto:><br>" +
            "Phone no.: +56 2 2307 3200 </br></br>" +
            "User(s) are requested to please provide the following information in their query or complaint:" +
            "<ul>" +
            "<li>Identification of the information provided; </li>" +
            "<li>Clear statement as to whether the information is PII or very sensitive personal information;</li>" +
            "<li>Address, telephone number or email address of complainant;</li>" +
            "</ul>" +
            "</li>" +
            "<li class=decimal><u><strong>REVISION OF POLICY</strong></u>" +
            "<p>The providers of the SNN Application reserve the right to revise, amend or modify this Policy at any time and in any manner, according to its requirement. Any change or revision will be communicated to the User along with the date when the modification was made.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>ACCESSING AND UPDATING PII </strong></u>" +
            "<p>When the User uses the SNN Application and its Services, the providers of the SNN Application make good faith efforts to provide the User, as and when requested by the User, with access to his/her PII and shall further ensure that any PII or sensitive personal data or information found to be inaccurate or deficient shall be corrected or amended as feasible, subject to any requirement for such PII or sensitive personal data or information to be retained by law or for legitimate business purposes. The providers of the SNN Application asks individual users and entities to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and the providers of the SNN Application may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup tapes), or for which access is not otherwise required. </p>" +
            "</li>" +
            "<li class=decimal><u><strong>GENERAL DATA PROTECTION REGULATIONS</stro" +
            "" +
            "" +
            "" +
            "ng></u>" +
            "<p>While dealing with data subjects of the European Union, the providers of the SNN Application take measures to comply with General data Protection Regulation (GDPR). Under GDPR, User(s) have the right to access their PII submitted to the providers of the SNN Application for any purpose. The Users can get access to their PII across any services at any time.</p>" +
            "</li>" +
            "<li class=decimal><u><strong>WITHDRAWAL OF CONSENT</strong></u>" +
            "<p>The consent provided to the providers of the SNN Application for collection and use of PII may be withdrawn at any time by contacting at <mailto:contacto@i4t.cl>contacto@i4t.cl</mailto:></p>" +
            "</li>" +
            "<li class=decimal><u><strong>USER ACKNOWLEDGEMENTS</strong></u>" +
            "<p>The User hereby acknowledges and agrees that this Privacy Policy:</p>" +
            "<ol type=i>" +
            "<li> Is clear and easily accessible and provide statements of Company policies and practices with respective to the Information;</li>" +
            "<li> Provides for the various types of personal or sensitive personal data of information to be collected;</li>" +
            "<li> Provides for the purposes of collection and usage of the Information;</li>" +
            "<li> Provides for disclosure of Information; and</li>" +
            "<li> Provides for reasonable security practices and procedures.</li>" +
            "</ol>" +
            "</li>" +
            "</ol>" + "<br>" +
            "<u><sup>1</sup> developed by Arresto Solutions Pvt. Ltd. </u>" +
            "</html>";
    String webData_spenish = webData;
    String server_alert = "<html>" +
            "<h3 align=center>&quotSNN Application Updation&quot</h3>" +
            "<p>Dear Valued Customer,</p>" +
            "<p>We wish you a Merry Christmas and a Happy New Year, and hope you are safe and doing well in these rather difficult times of COVID.</p>" +
            "<p>Last year had its share of challenges, but the silver lining in those dark clouds was your continuous support. We want to take this opportunity to thank you for using the application and making it successful. There are more than 1300 members using the app and the family is growing rapidly.</p>" +
            "<p>Each day new devices and technologies are emerging. To improve your overall experience in using the application across all devices, it is important that we take some necessary time to do upgrades. We have many new features that have been tested and now need to be uploaded on the App Store and Google Play.</p>" +
            "<p>Since it is traditionally a slow work time this coming week, we plan to shut down the SNN application temporarily from the 25th to the 31st of December 2020. In that time we plan to add some fantastic new features as part of the upgrade. The SNN application will be fully functional again by January 1st, 2021.</p>" +
            "<p>Thanks for your understanding and your continuous support.</p>" +
            "<p>Happy holidays to all.</p>" +
            "</html>";
}
